### ISSUE TITLE
Error when run local SLPred

### ISSUE THREAD

**Issue by Neo-xbx-00** [gozsari/SLPred#1]
Log file for running SLPred:
Descriptor type: GAAC
Descriptor type: CKSAAP
Descriptor type: CKSAAGP
Descriptor type: GDPC
Descriptor type: Moran
Descriptor type: Geary
Descriptor type: NMBroto
Descriptor type: CTDC
Descriptor type: CTDD
Descriptor type: CTDT
Descriptor type: CTriad
Descriptor type: KSCTriad
Descriptor type: SOCNumber
Descriptor type: QSOrder
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
     onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'
Traceback (most recent call last):
  File "POSSUM_Standalone_Toolkit/src/possum.py", line 68, in <module>
    onlyfiles = [ f for f in listdir(pssmdir) if isfile(join(pssmdir,f)) ]
FileNotFoundError: [Errno 2] No such file or directory: 'input_files/pssm_files'

**Comment by gozsari** [comment]
This is caused because PSSMs of the sequences could not be produces. The reasons may vary: 1- NCBI-blast is not working properly , 2- There is nit hit of your sequences with our sequence database that we use to produce PSSMs. If you need extra support, please let me know.
